-- MySQL Script generated by MySQL Workbench
-- Tue Jan  8 17:18:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_up2date
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_up2date
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_up2date` DEFAULT CHARACTER SET utf8 ;
USE `db_up2date` ;

-- -----------------------------------------------------
-- Table `db_up2date`.`tbl_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_up2date`.`tbl_users` (
  `id` INT(11) UNSIGNED NOT NULL,
  `email` VARCHAR(1000) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `salt` VARCHAR(100) NOT NULL,
  `creation_date` INT(11) NOT NULL,
  `role` BINARY(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_up2date`.`tbl_user_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_up2date`.`tbl_user_details` (
  `user_id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(250) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  INDEX `fk_tbl_user_details_tbl_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_tbl_user_details_tbl_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_up2date`.`tbl_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_up2date`.`tbl_user_auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_up2date`.`tbl_user_auth` (
  `user_id` INT(11) UNSIGNED NOT NULL,
  `auth_code` VARCHAR(200) NOT NULL,
  `ip_address` VARCHAR(50) NOT NULL,
  `expiration` INT(11) UNSIGNED NOT NULL,
  INDEX `fk_table4_tbl_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_table4_tbl_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_up2date`.`tbl_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
